# Generated by Django 5.2.6 on 2025-09-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_github_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='points_to_unlock',
            field=models.IntegerField(default=0),
        ),
    ]
