# Generated by Django 5.2.6 on 2025-09-12 14:36

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('coding', '0001_initial'), ('coding', '0002_remove_codingsession_end_time_and_more'), ('coding', '0003_codingsession_session_id'), ('coding', '0004_remove_codingsession_session_id'), ('coding', '0005_codingsession_status'), ('coding', '0006_codingsession_session_name')]

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('manual', 'Manual Entry'), ('github', 'GitHub')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credits_awarded', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_sessions', to='users.profile')),
                ('duration', models.DurationField(default=datetime.timedelta(0))),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('unlocked', 'Unlocked')], default='locked', max_length=10)),
                ('session_name', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
