# Generated by Django 5.2.6 on 2025-09-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0004_remove_codingsession_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingsession',
            name='status',
            field=models.CharField(choices=[('locked', 'Locked'), ('unlocked', 'Unlocked')], default='locked', max_length=10),
        ),
    ]
