# Generated by Django 5.2.6 on 2025-09-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0005_codingsession_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingsession',
            name='session_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
