name: CD of Code_To_Nature

on:
  push:
    branches: [ "Dev-Playground" ]
  pull_request:
    branches: [ "Dev-Playground" ]

jobs:
   deploy:
    runs-on: ubuntu-latest

    environment: develop
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run database migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          python manage.py migrate
      
      - name: Trigger Render deploy
        run: |
          curl "${{ secrets.DEPLOY_HOOK }}"
        